---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: centos-7
    driver_config:
      provision_command:
        - yum -y install iproute
      run_command: /usr/sbin/init
      privileged: true
  - name: centos-6
    driver_config:
      privileged: true

suites:
  - name: default
    run_list:
      - recipe[nginx_server-test::default]
    attributes:
