---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: centos-7
    driver_config:
      provision_command:
        - yum -y install iproute
      run_command: /usr/sbin/init
      privileged: true
  - name: centos-6
    driver_config:
      privileged: true

suites:
  - name: minimal
    run_list:
      - recipe[nginx_server-test::minimal]
    attributes:
  - name: kitchen_sink
    run_list:
      - recipe[nginx_server-test::kitchen_sink]
    attributes:
  - name: upstream
    run_list:
      - recipe[nginx_server-test::upstream]
    attributes:
