Metrics/LineLength:
  Exclude:
    - 'test/integration/minimal/serverspec/nginx_spec.rb'
Style/WordArray:
  Exclude:
    - 'test/fixtures/cookbooks/nginx_server-test/recipes/kitchen_sink.rb'
Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - 'test/fixtures/cookbooks/nginx_server-test/recipes/kitchen_sink.rb'
