Metrics/LineLength:
  Exclude:
    - 'test/integration/default/serverspec/nginx_spec.rb'
Style/WordArray:
  Exclude:
    - 'test/fixtures/cookbooks/nginx_server-test/recipes/default.rb'
Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - 'test/fixtures/cookbooks/nginx_server-test/recipes/default.rb'
